### ISSUE TITLE
Benennung der Datenpunkte

### ISSUE THREAD

**Issue by KoMa1978** [aendue/ioBroker.reolink#16]
Hi,

ist auch nur Kosmetik, aber die erstellten Datenpunkte heißen z.B.

ID: emailnotification

Hier fände ich es gut, zur besseren Lesbarkeit z.B. "EmailNotification" zu nutzen. Das wird bei einigen Datenpunkten ja auch schon gemacht.

Viel wichtiger wäre mir aber der Name, der hier "E-Mail Benachrichtigung" heißt.
Hier wäre es klasse, wenn man den Namen erstellen würde aus "reolink.0.device.name" und dem Namen (z.B. CAM Eingang.Email-Benachrichtigung).

Der Daikin Adapter (https://github.com/Apollon77/ioBroker.daikin/blob/master/README.md) macht das z.B. und das erleichtert die Nutzung in Scripten enorm, da ansonsten im Blockly nur 6x "E-Mail Benachrichtigung" auf 1 oder 0 geschaltet werden und man nur raten kann welche Kamera gemeint ist.

KoMa1978

**Comment by aendue** [comment]
Hallo, danke für dein Feedback...schau ich mir an!

**Comment by aendue** [comment]
Hallo,
im State EmailNotification wird jetzt der Name <adapter.instanz.device.name>_Emailnotify verwendet.

Damit der neue EmailNotification State angelegt werden kann, muss der alte manuell gelöscht werden.
Das liegt daran, dass der alte state über die jsonConfig.json erstellt wurde und mittels deleteState() nicht gelöscht werden kann. Der neue State wird dynamisch angelegt. 

Bitte mal testen. Danke!

**Comment by KoMa1978** [comment]
Mache ich gerne am Sonntag. Wie kann ich den Adapter mit gleicher Versionsnummer (0.1.0) aktualisieren?
Geht das einfach über einen erneuten Install oder muss ich den Adapter, die Instanzen und Datenpunkte erst komplett entfernen?

**Comment by KoMa1978** [comment]
Ignoriere das von eben ... Hab den Adapter entfernt und neu installiert ...

Sieht seeeehr gut aus. Jetzt kann man im Blockly auch schön sehen, was man gerade ändert ;-)

![image](https://user-images.githubusercontent.com/57285166/198648178-aed24a73-28c4-4b9e-879b-9e33414abf87.png)

**Comment by aendue** [comment]
Sehr gut...freut mich sehr! Issue mach ich dann zu. Danke
