### ISSUE TITLE
motion detection - motion/person/vehicle

### ISSUE THREAD

**Issue by hubbling** [aendue/ioBroker.reolink#26]
Einige Kameras können zwischen allgemeinen Bewegungen/Personen/Fahrzeugen differenzieren und selektiv triggern.
Der Adapter kennt nur "motion" true/false und springt bei jeglicher Bewegung auf true.

Es wäre schön, wenn  diese Differenzierung zwischen den Auslöser-Typen auch im Adapter gelänge!
Oder alternativ, wenn die Trigger-Einstellung der App übernommen würde.

**Comment by TommeDE** [comment]
moinmoin ...
ich habe das mit Loxone bereits über http Zugriff gelöst ... vielleicht hilft euch das ... 

http://192.168.x.x/api.cgi?cmd=GetAiState&channel=2&user=admin&password=0815

als Antwort kommt dann das:

[ { "cmd" : "GetAiState", "code" : 0, "value" : { "channel" : 2, "dog_cat" : { "alarm_state" : 0, "support" : 0 }, "face" : { "alarm_state" : 0, "support" : 0 }, "people" : { "alarm_state" : 0, "support" : 1 }, "vehicle" : { "alarm_state" : 0, "support" : 1 } } } ]

und dann ist das der Alarmstate ... Support sagt was davon die Kamera unterstützt
ich würde mich auch über eine Adapterintegration freuen!

es grüßt der Tomme

**Comment by TommeDE** [comment]
ergänzend ... bei mir hängen die Cams an einem Reo NVR

**Comment by bertl83** [comment]
Wäre auch für eine Integration in den Adapter. 
Hab eine RLC-830A

**Comment by aendue** [comment]
Hallo, ich schau Jed mir unter der Woche mal an. Sollte eigentlich kein Problem sein. Melde mich zum testen. DankeViele GrüßeAndyAm 13.08.2023 um 16:54 schrieb bertl83 ***@***.***>:﻿
Wäre auch für eine Integration in den Adapter.
Hab eine RLC-830A

**Comment by aendue** [comment]
Hallo, im aktuellen Commit auf Github wird nun zwischen den erkannten Objekten unterschieden:
Dog_Cat
Face
People
Vehicle

Im Objektexplorer sieht es so aus:
![image](https://github.com/aendue/ioBroker.reolink/assets/8988228/be3b9bb9-d139-415e-a16e-b1422a02ae21)

Im debug-Log wird es so ausgegeben:
![image](https://github.com/aendue/ioBroker.reolink/assets/8988228/82966c17-7f7b-4374-a03e-e73a618c3305)

Bitte testen. Wenn alles io ist mach ich den npm release.

Viele Grüße
Andy

**Comment by ChristophEngelHH** [comment]
@aendue Hast du eine Idee an was das liegen kann?

**Comment by aendue** [comment]
Hallo, ich schau es mir die Woche mal an und melde mich nochmal.Viele GrüßeAndy Am 29.08.2023 um 08:59 schrieb Christoph Engel ***@***.***>:﻿
@aendue Hast du eine Idee an was das liegen kann?

**Comment by aendue** [comment]
Hallo, ich hab es bei mir ausprobiert und da funktioniert es gut. Welches Kameramodel hast du?Viele GrüßeAndyAm 29.08.2023 um 08:59 schrieb Christoph Engel ***@***.***>:﻿
@aendue Hast du eine Idee an was das liegen kann?

**Comment by bertl83** [comment]
> Hallo, im aktuellen Commit auf Github wird nun zwischen den erkannten Objekten unterschieden: Dog_Cat Face People Vehicle
> 
> Im Objektexplorer sieht es so aus: ![image](https://user-images.githubusercontent.com/8988228/261321863-be3b9bb9-d139-415e-a16e-b1422a02ae21.png)
> 
> Im debug-Log wird es so ausgegeben: ![image](https://user-images.githubusercontent.com/8988228/261321304-82966c17-7f7b-4374-a03e-e73a618c3305.png)
> 
> Bitte testen. Wenn alles io ist mach ich den npm release.
> 
> Viele Grüße Andy

Sorry für die blöde Frage, wie bekomm ich den Commit denn in meinen IOBroker rein? Dann würd ich das ganze auch mal testen.

**Comment by bertl83** [comment]
Mit meiner RLC-830A funktioniert.

**Comment by ChristophEngelHH** [comment]
@aendue Ich habe eine RLC-510WA über LAN angeschlossen. Ich habe den Adapter auch nochmal auf einer anderen Instanz installiert und habe dort das gleiche Vorkommen. Debug output s.o. Gib gern Bescheid, wenn du noch weitere Daten zur Prüfung brauchst.

**Comment by aendue** [comment]
Hallo, ich kann das leider nicht nachvollziehen. Hab auch eine RLC510 POE und bei mir funktioniert es. Welche Firmware hast die installiert?Viele GrüßeAndyAm 06.09.2023 um 21:27 schrieb Christoph Engel ***@***.***>:﻿
@aendue Ich habe eine RLC-510WA über LAN angeschlossen. Ich habe den Adapter auch nochmal auf einer anderen Instanz installiert und habe dort das gleiche Vorkommen. Debug output s.o. Gib gern Bescheid, wenn du noch weitere Daten zur Prüfung brauchst.

**Comment by DennisH1978** [comment]
Bei mir dasselbe. Allerdings mit der Doorbell. Erkennt keinerlei Bewegung. Kommt zumindest im IoBroker nicht an.

**Comment by ChristophEngelHH** [comment]
@aendue Danke für den Hinweis mit der Firmware! Ich habe die grade aktualisiert und ohne etwas anderes geändert zu haben läuft es *thumbsup*
neue Firmware: v3.1.0.764 (alte Firmware Version habe ich leider nicht aufgeschrieben :-/ Hoffe dem einen oder anderen hilft es hier ebenfalls!

**Comment by oelison** [comment]
#49 ist vielleicht ein ähnliches Problem für manche Kameras. Nur als hinweiß.
