### ISSUE TITLE
reolink has an invalid jsonConfig:

### ISSUE THREAD

**Issue by ebgonline** [aendue/ioBroker.reolink#40]
**Describe the bug**  
Errormessage from the admin-Adapter:
reolink has an invalid jsonConfig: [{"instancePath":"/items/_options/items/cameraProtocol","schemaPath":"#/patternProperties/%5E.%2B/allOf/22/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"newline"},"message":"must NOT have additional properties"},{"instancePath":"/items/_options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**To Reproduce**  
Install reolink-Adapter
**Expected behavior**  
Camera is found and datapoints are filled

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
starting. Version 1.0.1 (non-npm: aendue/ioBroker.reolink#42863bb6bd74194319503b855f95198849577cf9) in /opt/iobroker/node_modules/iobroker.reolink, node: v18.17.1, js-controller: 5.0.16
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: raspberryos (debian bullseye)

**Additional context**

**Comment by oelison** [comment]
I have tested it with a windows, linux and macOS. I have not seen this issue.

**Comment by ebgonline** [comment]
I am happy with you, but how does this help?
I didnt compare it, because it was installed from the github-repo and started.

**Comment by ticaki** [comment]
to check/reproduce this u need always the information about used admin version. 

There is no error in ur jsonConfig.json

**Comment by ebgonline** [comment]
Thats funny, because i installed the adapter actually from github, where this was fixed before.
now i get the log-entry from the reolink-adapter that says 
"TypeError [ERR_INVALID_URL]: Invalid URL: ERR_INVALID_URL"
That i cant understand, because nowhere in the config is something like "URL" or so.
My admin-Adapter is 6.12.0

**Comment by mcm1957** [comment]
@oelison 
Fixed with 1.0.2 or not?

**Comment by ebgonline** [comment]
fixed
