### ISSUE TITLE
Reolink NVR

### ISSUE THREAD

**Issue by Rocko84** [aendue/ioBroker.reolink#53]
Hello,

Is it possible to implement the Reolink NVRs like RLN12W? Due to a separate WLAN of the RLN12W it is not possible to get access over the adapter to the Reolink cameras. 
thanks

**Comment by oelison** [comment]
Hi, I do not know if this is possible. The description on the reolink site do not help here. Is there an API available?

**Comment by Rocko84** [comment]
Sorry but I don’t know if there is an api available. The last API is released in April 2023 and I think only for the reolink cameras. But maybe there comes a updated in the next time. I will contact reolink if there is a chance to get an api.

**Comment by Rocko84** [comment]
Hello,
I get an answer from reolink support team. They said, that you will find the API under following link for camera AND nvrs.
 
https://support-d.reolink.com/hc/en-us/articles/900004436163-How-to-Set-up-Reolink-Ports-Server-Settings-on-Reolink-NVR-New-UI

Is it now possible to implement the NVRs in the adapter?

**Comment by oelison** [comment]
This is an UI (user interface) not an API (aplication interface). It is not usable for the adapter.

**Comment by Rocko84** [comment]
Oh sorry little mistake from my site. Here ist the correct link
https://support-d.reolink.com/attachments/token/Rhwfzjvaqh0imdRCrhJZYhSgU/?name=Camera+HTTP+API+User+Guide_v8.pdf

the reolink support said, that is for both

**Comment by oelison** [comment]
When this is true, this should work out of the box and nothing need to be mopdified on the adapter.

**Comment by Rocko84** [comment]
Sorry but it doesn’t work. After start the adapter the following Error in the protocol is present:


reolink.0
2024-02-03 19:30:25.636	error	Error: self-signed certificate: DEPTH_ZERO_SELF_SIGNED_CERT

can anybody help?

**Comment by oelison** [comment]
You need to remove the check mark from validate the ssl certificate.

**Comment by Rocko84** [comment]
It works. Thank you so much
