### ISSUE TITLE
After Update Scheduled Error

### ISSUE THREAD

**Issue by spiecky** [aendue/ioBroker.reolink#77]
Hi,
after Update i have every 2 Minutes this Error in my Iobroker Protocol:

"An unknown scheduled recording state was detected: 21025648"

My Cam is a Duo 2 POE (newest FW)
Reolink Adapter 1.1.0 (in older Version i have no Error)
Node.js: v18.20.2(18.20.3)
NPM: 10.5.0(10.7.0)
Linux

Thx for help

**Comment by oelison** [comment]
I will degrade it to debug.

**Comment by oelison** [comment]
Please test in expert mode this bugfix.

**Comment by Nibbels** [comment]
Sorry, my fault. Its a habit to track weird values.
@spiecky can you check which what your recording state shows? Is there some specialty?
![grafik](https://github.com/aendue/ioBroker.reolink/assets/3265671/957c510d-e2a8-4d64-9341-d6fd9a320ba3)
(Source: Duo 3 PoE)

**Comment by spiecky** [comment]
Hi,
kann ich hier eigentlich auch auf deutsch schreiben ? Ist etwas einfacher :-)
Habe in der Cam eingestellt, dass sie Rund um die Uhr jede Bewegung inkl. Person, Fahrzeug und Tier aufzeichnet.
Auch wenn ich zum testen die Aufnahme deaktiviere (rote Kreise) kommt die Fehlermeldung.
![Screenshot 2024-06-09 203809](https://github.com/aendue/ioBroker.reolink/assets/133597685/a41340ad-89d8-465e-bfeb-a303159e03ae)
![Screenshot 2024-06-09 203931](https://github.com/aendue/ioBroker.reolink/assets/133597685/902f7236-b2fc-4807-a795-1feaa2375e2b)

**Comment by spiecky** [comment]
Hat der Fehler vlt. was mit den verschiedenen "Sensoren" zu tun ?
![Screenshot 2024-06-09 205117](https://github.com/aendue/ioBroker.reolink/assets/133597685/ee5d4d9a-6b01-4839-9558-0be8920cdb31)

**Comment by spiecky** [comment]
und das komische ist ja, dass der Fehler alle 2min kommt, obwohl die Cam keine Bewegung erkannt hat
![Screenshot 2024-06-09 210304](https://github.com/aendue/ioBroker.reolink/assets/133597685/3120ec93-5f10-44be-9f90-fc20d53d9683)

**Comment by spiecky** [comment]
Hi,
sooo.....habe meine Duo2 durch eine Duo3 ausgetauscht. Nicht wegen dem Fehler ;-) sondern wegen der Bildqualität. Danach hatte ich den o.g. Fehler nicht mehr aber einen anderen. Diesen konnte ich beheben in dem ich von Kanal 1 auf Kanal 0 umgestellt habe. Da ich die alte Duo2 nicht mehr habe, kann ich dies damit jetzt leider nicht mehr testen. Vielleicht wäre das auch die Lösung für den o.g. Fehler gewesen.

Aber falls Ihr Probleme mit der Verbindung zur Kamera hab, mal den Kanal umstellen und testen. Vielleicht hilft das ja.....

Trotzdem vielen Dank an alle Helfer :-)
