### ISSUE TITLE
Datenpunkte für reolink E1 Outdoor

### ISSUE THREAD

**Issue by csch25** [aendue/ioBroker.reolink#8]
In Bezug auf den Post im ioBroker-Forum [hier](https://forum.iobroker.net/topic/56116/neuer-adapter-reolink-kamera/118?_=1662909772595#) :

Ansteuern der PTZ Punkte sind für die Reolink E1 Outdoor schon mal super eingefügt,
ich würde mir mehr Datenpunkte wünschen

z.B. 
- Kalibrierung
- Wachpunkt auto / aus
- Alarm- Tracking an / aus
- Push Nachrichten an / aus
- Licht an / aus
- Audio 
- Sirene (Alarmton vorspielen) dann kann dieser ausgelöst werden

**Comment by csch25** [comment]
Ich kenne mich mit Programmierung ja nicht so aus, aber nachdem ich Deine Antwort gelesen habe, habe ich noch folgendes gefunden:

Ich hoffe die Links sind erlaubt, und ich übernehme keine Verantwortung dafür.
Der Link im Beitrag führt zu einem Google-Drive Download.
Bei mir konnte das Virenprogramm nichts finden, somit gehe ich davon aus, das es ok ist.

[https://www.reddit.com/r/reolinkcam/comments/rd847e/reolink_camera_api_user_guide_dec10_2021/](https://www.reddit.com/r/reolinkcam/comments/rd847e/reolink_camera_api_user_guide_dec10_2021/)

Vielleicht hilft das?

Falls ich mit dem Lik daneben liege bitte bescheid geben.

Ansonsten z.B. Audio:

[Screenshot](https://drive.google.com/file/d/1qEXreYlaCOTRdlm2EjUqKFeWUO_Mk8d3/view?usp=sharing)

1 - Ton Aufnehmen
2 - Lautstärke
3 - Alarmton abspielen

[oder Kalibrierung, Wachpunkt](https://drive.google.com/file/d/1eK1eqv2EoYfG4VkvrF8hsJj7hiqwn8mO/view?usp=sharing)

Aber ich glaube die Screenshots bringen Dich nicht weiter.
Was ich noch machen Könnet die oben genannte Datei Direkt senden, aber ich weis nicht ob ich damit irgendwelche Rechte verletze oder anderes falsch mache.

**Comment by oelison** [comment]
Das Dokument habe ich. Die Screenshots sind hilfreich. (habe eine Englische Oberfläche)
1 ist Audio aufnahme einschalten
2 ist Lautstärke des Lautsprechers
3 ist Lautstärke test
Kalibrierung und Wachpunkt habe ich nicht. Bitte beschreib mal was dann passiert. Dann kann ich die passenden Befehle vielleicht erahnen.

**Comment by csch25** [comment]
Wenn ich die Cam über Browser / IP abrufe habe ich auch nur die englische Oberfläche ohne die Punkte Wachpunkt oder Kalibrierung.
Bei Abruf mit Desktop-App oder Mobil-App habe ich die Punkte schon.

Wachpunkt ist eine festgelegte Position in die die Cam nach eingestellter Zeit (sofern auf Auto gestellt) zurückkehrt. Dies ist normal auch der Punkt an dem eine Überwachung stattfindet, da bei diese Punkt evtl. eingestellte Masken für Überwachung passen.

Evtl. http://IPC_IP/api.cgi?cmd=GetPtzGuard&token=TOKEN...  

[Screenshot Wachpunkt](https://drive.google.com/file/d/1wouwqLlvkuVip-TEuhNTjjfukCHp2q23/view?usp=sharing)


Kalibrierung, hier führt die Cam einfach eine Kalibrierungsfahrt durch, falls die PTZ- Punkte nicht mehr ganz passen.
Dies ist einfach der Button im Screenshot wie im Letzten Beitrag von mir.

[Screeshot Wachpunkt, unten Mitte aufgeführt](https://drive.google.com/file/d/1eK1eqv2EoYfG4VkvrF8hsJj7hiqwn8mO/view?usp=sharing)

Welche Befehle hier gesendet werde kann ich leider nicht sagen oder wüsste nicht wie diese ausgelesen werden könnten.
Ich bekomme es auch nicht hin Befehle per Kommandozeile / Win-Eingabeaufforderung über Windows zu senden um so evtl. zu testen.

Wie gesagt, ich kenn mich nicht aus, aber wenn ich versuche z.B.:

`curl -s -k -X POST -H "Content-Type : application/json" -d "[{"cmd": "GetPtzGuard","action": 0,"param": {"channel": 0}}]" "http://#IP#/cgi-bin/api.cgi?user=#username#&password=#password#"`

Daten wie  #IP# , 'username# , 'Password# wurden natürlich gesetzt, http und https wurde getestet,kommt die Ausgabe:

```
[
   {
      "cmd" : "Unknown",
      "code" : 1,
      "error" : {
         "detail" : "please login first",
         "rspCode" : -6
      }
   }
]
```

Ich würde gern testen, aber weis nicht wie?

**Comment by KoMa1978** [comment]
Hi zusammen,

ich würde mir die "Email-Benachrichtungen" (API-Commands SetEmailV20 und GetEmailV20) analog zu den o.g. PUSH Benachrichtigungen wünschen. Es geht mir nicht um die Konfiguration z.B. von Server oder Empfänger, sondern eigentlich nur um das Ein und Ausschalten.

Hintergrund:
Motion Detection möchte ich gerne immer an haben, eine Benachrichtigung per Mail aber nur, wenn ich nicht zu hause bin.

Besten Dank,
 KoMa1978

**Comment by aendue** [comment]
> Hi zusammen,
> 
> ich würde mir die "Email-Benachrichtungen" (API-Commands SetEmailV20 und GetEmailV20) analog zu den o.g. PUSH Benachrichtigungen wünschen. Es geht mir nicht um die Konfiguration z.B. von Server oder Empfänger, sondern eigentlich nur um das Ein und Ausschalten.
> 
> Hintergrund: Motion Detection möchte ich gerne immer an haben, eine Benachrichtigung per Mail aber nur, wenn ich nicht zu hause bin.
> 
> Besten Dank, KoMa1978

Hallo, ich schau mal in der API nach icb das machbar ist.

**Comment by KoMa1978** [comment]
> Hallo, ich schau mal in der API nach ob das machbar ist.
Hi,

ich hatte vor Wochen/Monaten mal etwas mit JS getestet, bin aber leider kein Programmierer. Ich konnte es aber ein/ausschalten:

varHTTPOPTIONS = {
                    url: "https://" + varHOST + "/cgi-bin/api.cgi?token=" + varTOKEN,
                    method: 'GET',
                    form: '[{"cmd":"SetEmailV20","param":{"Email":{"enable":' + varSWITCH + '}}}]'
                };

varTOKEN ist der Login Token
varSWITCH = "1" für an und "0" für aus.

Und dann mit "request(varHTTPOPTIONS, async function (varERROR, varRESPONSE, varBODY) { ... "
KoMa1978

**Comment by aendue** [comment]
> > Hallo, ich schau mal in der API nach ob das machbar ist.
> > Hi,
> 
> ich hatte vor Wochen/Monaten mal etwas mit JS getestet, bin aber leider kein Programmierer. Ich konnte es aber ein/ausschalten:
> 
> varHTTPOPTIONS = { url: "https://" + varHOST + "/cgi-bin/api.cgi?token=" + varTOKEN, method: 'GET', form: '[{"cmd":"SetEmailV20","param":{"Email":{"enable":' + varSWITCH + '}}}]' };
> 
> varTOKEN ist der Login Token varSWITCH = "1" für an und "0" für aus.
> 
> Und dann mit "request(varHTTPOPTIONS, async function (varERROR, varRESPONSE, varBODY) { ... " aufgerufen.
> 
> Danke Dir, damit wäre mir sehr geholfen. Ich kann das auch gerne mit eine E1 Outdoor testen,
> 
> KoMa1978

Jupp, hab ich vorhin auch gesehen. Hab es auch schon eingebaut und wenn ich es schaffe heute Abend commiten.

**Comment by KoMa1978** [comment]
Email-Notification AN/AUS funktioniert in ersten Tests ... Danke
